### PR TITLE
[Unity] Code Examples Updated, Typos Fixed

### PR DESCRIPTION
**Pull request by AliRKat**

### CODE REVIEW

**Comment by AliRKat** [comment]
[[Unity, doc] Update other code examples not to use "{}" initialization. remove empty lines after some code comments](https://trello.com/c/Jpp31m8v/1166-unity-doc-update-other-code-examples-not-to-use-initialization-remove-empty-lines-after-some-code-comments)

**Comment by ArtursKadikis** [comment]
image
change all code examples to be similar to this

**Comment by ArtursKadikis** [comment]
image
last code block example is missing tabbing

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
pls adjust the code block style

**Review by ArtursKadikis — APPROVED** [review]

**Pull request merged**
