### PR TITLE
[SDK 436] C++ documentation

### PR DESCRIPTION
**Pull request by ZahidZafar**

### CODE REVIEW

**Comment by ArtursKadikis** [comment]
image
These sections should have been reworked into "Adding the SDK to the project"

image
Adding metrics is not required.

image
C++ does not have these data types.

image
Remove this, add a better intro.

image
It's lacking a section for device ID management.

image
Be more explicit about the required keys. Format it better.

image
This is out of place, remove it.

**Comment by ArtursKadikis** [comment]
Rework the appKey, server url section so that it’s similar to the following image. Use the following url “https://support.count.ly/hc/en-us/articles/900000908046-Getting-started-with-SDKs#acquiring-your-application-key-and-server-url”.

image

**Comment by ZahidZafar** [comment]
SDK doesn't have these features

* Device ID management
 - Device ID generation - should describe all the ways the ID is generated (when no custom id is provided by the dev) and what platform information is used to do that
 - Changing device ID  - should describe ways to do it with and without merge
 - Temporary Device ID
 - Retrieving current device ID - should include also a way to retrieve the current ID type
 - Consent

**Comment by ZahidZafar** [comment]
We don't have these features.

* Device ID management
 - Device ID generation - should describe all the ways the ID is generated (when no custom id is provided by the dev) and what platform information is used to do that
 - Changing device ID  - should describe ways to do it with and without merge
 - Temporary Device ID
 - Retrieving current device ID - should include also a way to retrieve the current ID type
 - Consent

**Comment by ArtursKadikis** [comment]
Please also mention how to update the automatic session update time interval

**Comment by ArtursKadikis** [comment]
image
provide more information of what the mandatory fields are.

image
The lower sections are redundant and should be removed.

image
Should be renamed to "SDK logging mode".

image
This section isn't explaining anything on where it is stored.

image
This has no place in the doc and should be removed.

image
Fix code styling.

image

This should be removed.

image
This should be reworked. All parameters should be shown explicitly and all options should be explained.


image
Duplicate sections should be removed.

**Pull request merged**
