### PR TITLE
[SDK 911] [C++] Crash section added

### PR DESCRIPTION
**Pull request by ZahidZafar**

### CODE REVIEW

**Review by turtledreams — APPROVED** [review]

**Review by ArtursKadikis — CHANGES_REQUESTED** [review]
All mandatory fields with their keys need to be mentioned in the "crash metrics" explanation.
It should also mention what would happen if the mendatory fields are not added - crash would not show up.

**Comment by ArtursKadikis** [comment]
the mandatory useage should be reflected in the example

**Comment by ArtursKadikis** [comment]
add a callout to the crash section about the version requirement

**Comment by ArtursKadikis** [comment]
Current should also be updated

**Comment by ArtursKadikis** [comment]
add the .X

**Review by ArtursKadikis — APPROVED** [review]

**Pull request merged**
